### ISSUE TITLE
Assign markers for mashup into data attribute.

### ISSUE THREAD

**Issue by zogot** [pronamic/wp-pronamic-google-maps#14]
This allows for developers to reference the markers for their own purposes.  Useful for requests like so:

http://wordpress.org/support/topic/link-to-map-and-location-info?replies=2#post-4541792

**Comment by remcotolsma** [comment]
For now, we have decided to no longer maintain and develop the "Pronamic Google Maps" plugin. Therefore, we will close this issue and archive this repository.
