### ISSUE TITLE
Allow the use of font icons as markers instead of images 

### ISSUE THREAD

**Issue by ccarrascom** [pronamic/wp-pronamic-google-maps#26]
Hello,
I would like to use this library http://map-icons.com/ in order to print font icons as markers instead ok images.
This library extends the google maps marker class in order to output HTML for the markers.
This is just a suggestion so please let me know if this kind of support is on your plans or if i can collaborate with you.
Thanks!

**Comment by remcotolsma** [comment]
For now, we have decided to no longer maintain and develop the "Pronamic Google Maps" plugin. Therefore, we will close this issue and archive this repository.
