### ISSUE TITLE
Mashup Filter?

### ISSUE THREAD

**Issue by konus1** [pronamic/wp-pronamic-google-maps#32]
Hello, would it be possible to add a dynamic filter to the map?
Example http://www.dd4kids.de/wp-content/uploads/karte/karte.html
or
https://moreoutdoors.net/all-in-one-map/?h=1160
or
http://what2do.tips/

**Comment by remcotolsma** [comment]
This is currently not supported in the Pronamic Google Maps plugin, we also don't have concrete plans to develop support for it, but we will add it to the todo/wishlist.
