### ISSUE TITLE
Mapclusterer icons no longer working

### ISSUE THREAD

**Issue by mbshah48207** [pronamic/wp-pronamic-google-maps#35]
The link to the map clusterer icons has moved (https://github.com/tomchentw/react-google-maps/issues/255). I was able to work around this by changing my marker_clusterer_options as follows:

`				'marker_clusterer_options' => array(
					'gridSize' => 30,
					'imagePath' => 'https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m',
				),
`

I don't know how to use Git -- could someone please update the examples/mashup-marker-clusterer.php file?

**Comment by rvdsteege** [comment]
This issue was fixed in https://github.com/pronamic/wp-pronamic-google-maps/commit/704ef2a54b614750cbe04bdb607a85dcac781cf4, but an updated version of the plugin has not been released yet.

**Comment by remcotolsma** [comment]
We just launched version `2.3.2` of the Pronamic Google Maps plugin on WordPress.org: https://wordpress.org/plugins/pronamic-google-maps/.
