### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by martajohnsson** [pronamic/wp-pronamic-google-maps#5]
Hi, I try to use filter from https://github.com/pronamic/wp-pronamic-google-maps/blob/master/examples/mashup-post-type-a-b-marker-icon.php buit can't get it work; can somebody help me please?

**Comment by remcotolsma** [comment]
For now, we have decided to no longer maintain and develop the "Pronamic Google Maps" plugin. Therefore, we will close this issue and archive this repository.
